[package]
name = "rapinsel-backend"
version = "0.1.0"
edition = "2021"
authors = ["Olaf Luijks <olafluijks@proton.me>"]
license = "MIT"
readme = "README.md"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.8.0"
async-trait = "0.1.80"
chrono = { version = "0.4.38", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.11.3"
futures-util = "0.3.30"
num_cpus = "1.16.0"
openssl-probe = "0.1.5"
lazy_static = "1.5.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120", features = ["preserve_order"] }
sqlx = { version = "0.7.4", features = [
  "tls-native-tls",
  "runtime-async-std",
  "postgres",
  "chrono",
  "uuid",
  "macros",
] }
tokio = { version = "1.38.0", features = ["full"] }
validator = { version = "0.16", features = ["derive"] }
uuid = { version = "1.9.1", features = ["serde", "v4"] }
