version: "3.9"
services:
  db:
    image: ${DOCKER_IMAGE}
    container_name: ${CONTAINER_NAME}
    shm_size: 128mb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    # sudo chown -R you:you data
    user: 1000:1000
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
